# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addFixDriverForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addFixDriver(object):
    def setupUi(self, addFixDriver):
        addFixDriver.setObjectName("addFixDriver")
        addFixDriver.resize(400, 300)
        addFixDriver.setMaximumSize(QtCore.QSize(400, 300))
        self.verticalLayout = QtWidgets.QVBoxLayout(addFixDriver)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(addFixDriver)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.autosBox = QtWidgets.QComboBox(addFixDriver)
        self.autosBox.setObjectName("autosBox")
        self.verticalLayout.addWidget(self.autosBox)
        self.label_2 = QtWidgets.QLabel(addFixDriver)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.driversBox = QtWidgets.QComboBox(addFixDriver)
        self.driversBox.setObjectName("driversBox")
        self.verticalLayout.addWidget(self.driversBox)
        self.category = QtWidgets.QLabel(addFixDriver)
        self.category.setObjectName("category")
        self.verticalLayout.addWidget(self.category)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(addFixDriver)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(addFixDriver)
        self.buttonBox.accepted.connect(addFixDriver.accept)
        self.buttonBox.rejected.connect(addFixDriver.reject)
        QtCore.QMetaObject.connectSlotsByName(addFixDriver)

    def retranslateUi(self, addFixDriver):
        _translate = QtCore.QCoreApplication.translate
        addFixDriver.setWindowTitle(_translate("addFixDriver", "Закрепление водителя"))
        self.label.setText(_translate("addFixDriver", "<html><head/><body><p>Транспортное средство</p></body></html>"))
        self.label_2.setText(_translate("addFixDriver", "Водитель"))
        self.category.setText(_translate("addFixDriver", "\"категория\""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addFixDriver = QtWidgets.QDialog()
    ui = Ui_addFixDriver()
    ui.setupUi(addFixDriver)
    addFixDriver.show()
    sys.exit(app.exec_())
