# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FixedDriverForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FixedDriverList(object):
    def setupUi(self, FixedDriverList):
        FixedDriverList.setObjectName("FixedDriverList")
        FixedDriverList.resize(484, 414)
        FixedDriverList.setMaximumSize(QtCore.QSize(608, 414))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(FixedDriverList)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fixedDriverTable = QtWidgets.QTableWidget(FixedDriverList)
        self.fixedDriverTable.setObjectName("fixedDriverTable")
        self.fixedDriverTable.setColumnCount(0)
        self.fixedDriverTable.setRowCount(0)
        self.horizontalLayout.addWidget(self.fixedDriverTable)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.insertFixedDriver = QtWidgets.QPushButton(FixedDriverList)
        self.insertFixedDriver.setObjectName("insertFixedDriver")
        self.verticalLayout.addWidget(self.insertFixedDriver)
        self.udapeFixedDriver = QtWidgets.QPushButton(FixedDriverList)
        self.udapeFixedDriver.setObjectName("udapeFixedDriver")
        self.verticalLayout.addWidget(self.udapeFixedDriver)
        self.deleteFixedDriver = QtWidgets.QPushButton(FixedDriverList)
        self.deleteFixedDriver.setObjectName("deleteFixedDriver")
        self.verticalLayout.addWidget(self.deleteFixedDriver)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(FixedDriverList)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(FixedDriverList)
        QtCore.QMetaObject.connectSlotsByName(FixedDriverList)

    def retranslateUi(self, FixedDriverList):
        _translate = QtCore.QCoreApplication.translate
        FixedDriverList.setWindowTitle(_translate("FixedDriverList", "Закрепление водителя"))
        self.insertFixedDriver.setText(_translate("FixedDriverList", "Закрепить\n"
"водителя"))
        self.udapeFixedDriver.setText(_translate("FixedDriverList", "Изменить\n"
"закрепление"))
        self.deleteFixedDriver.setText(_translate("FixedDriverList", "Удалить\n"
"закрепление"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FixedDriverList = QtWidgets.QDialog()
    ui = Ui_FixedDriverList()
    ui.setupUi(FixedDriverList)
    FixedDriverList.show()
    sys.exit(app.exec_())
