# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'listAutoForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_autoList(object):
    def setupUi(self, autoList):
        autoList.setObjectName("autoList")
        autoList.setWindowModality(QtCore.Qt.ApplicationModal)
        autoList.resize(454, 537)
        autoList.setMaximumSize(QtCore.QSize(16777215, 16777211))
        self.horizontalLayout = QtWidgets.QHBoxLayout(autoList)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableAuto = QtWidgets.QTableWidget(autoList)
        self.tableAuto.setLineWidth(1)
        self.tableAuto.setObjectName("tableAuto")
        self.tableAuto.setColumnCount(3)
        self.tableAuto.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableAuto.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAuto.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAuto.setHorizontalHeaderItem(2, item)
        self.tableAuto.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.tableAuto)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.newAuto = QtWidgets.QPushButton(autoList)
        self.newAuto.setMaximumSize(QtCore.QSize(16777212, 16777215))
        self.newAuto.setObjectName("newAuto")
        self.verticalLayout_2.addWidget(self.newAuto)
        self.editAuto = QtWidgets.QPushButton(autoList)
        self.editAuto.setObjectName("editAuto")
        self.verticalLayout_2.addWidget(self.editAuto)
        self.deleteAuto = QtWidgets.QPushButton(autoList)
        self.deleteAuto.setObjectName("deleteAuto")
        self.verticalLayout_2.addWidget(self.deleteAuto)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(autoList)
        QtCore.QMetaObject.connectSlotsByName(autoList)

    def retranslateUi(self, autoList):
        _translate = QtCore.QCoreApplication.translate
        autoList.setWindowTitle(_translate("autoList", "Список транспортных средств"))
        item = self.tableAuto.horizontalHeaderItem(0)
        item.setText(_translate("autoList", "№"))
        item = self.tableAuto.horizontalHeaderItem(1)
        item.setText(_translate("autoList", "Гос номер"))
        item = self.tableAuto.horizontalHeaderItem(2)
        item.setText(_translate("autoList", "Марка\\модель"))
        self.newAuto.setText(_translate("autoList", "Новое ТС"))
        self.editAuto.setText(_translate("autoList", "Редактировать ТС"))
        self.deleteAuto.setText(_translate("autoList", "Удалить ТС"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    autoList = QtWidgets.QDialog()
    ui = Ui_autoList()
    ui.setupUi(autoList)
    autoList.show()
    sys.exit(app.exec_())
