# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newAutoForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_newAuto(object):
    def setupUi(self, newAuto):
        newAuto.setObjectName("newAuto")
        newAuto.resize(553, 446)
        self.verticalLayout = QtWidgets.QVBoxLayout(newAuto)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(newAuto)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.modelAuto = QtWidgets.QLineEdit(newAuto)
        self.modelAuto.setObjectName("modelAuto")
        self.verticalLayout.addWidget(self.modelAuto)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(newAuto)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.gosNomer = QtWidgets.QLineEdit(newAuto)
        self.gosNomer.setMaximumSize(QtCore.QSize(100, 16777215))
        self.gosNomer.setObjectName("gosNomer")
        self.verticalLayout_2.addWidget(self.gosNomer)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.noNomer = QtWidgets.QCheckBox(newAuto)
        self.noNomer.setObjectName("noNomer")
        self.horizontalLayout.addWidget(self.noNomer)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_4 = QtWidgets.QLabel(newAuto)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.typeAuto = QtWidgets.QComboBox(newAuto)
        self.typeAuto.setObjectName("typeAuto")
        self.verticalLayout.addWidget(self.typeAuto)
        self.label_3 = QtWidgets.QLabel(newAuto)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.cat_auto = QtWidgets.QComboBox(newAuto)
        self.cat_auto.setObjectName("cat_auto")
        self.verticalLayout.addWidget(self.cat_auto)
        self.line = QtWidgets.QFrame(newAuto)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_5 = QtWidgets.QLabel(newAuto)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.skzi = QtWidgets.QCheckBox(newAuto)
        self.skzi.setObjectName("skzi")
        self.horizontalLayout_2.addWidget(self.skzi)
        self.estr = QtWidgets.QCheckBox(newAuto)
        self.estr.setObjectName("estr")
        self.horizontalLayout_2.addWidget(self.estr)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(newAuto)
        self.buttonBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(newAuto)
        self.buttonBox.accepted.connect(newAuto.accept)
        self.buttonBox.rejected.connect(newAuto.reject)
        QtCore.QMetaObject.connectSlotsByName(newAuto)

    def retranslateUi(self, newAuto):
        _translate = QtCore.QCoreApplication.translate
        newAuto.setWindowTitle(_translate("newAuto", "Новое транспортное средство"))
        self.label.setText(_translate("newAuto", "Маркамодель транспортного средства"))
        self.label_2.setText(_translate("newAuto", "Государственный регистрационный знак"))
        self.noNomer.setText(_translate("newAuto", "Без номера"))
        self.label_4.setText(_translate("newAuto", "Типа транспортного средства"))
        self.label_3.setText(_translate("newAuto", "Необходимая категория для управления"))
        self.label_5.setText(_translate("newAuto", "Необходимы карты тахографа"))
        self.skzi.setText(_translate("newAuto", "СКЗИ"))
        self.estr.setText(_translate("newAuto", "ЕСТР"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    newAuto = QtWidgets.QDialog()
    ui = Ui_newAuto()
    ui.setupUi(newAuto)
    newAuto.show()
    sys.exit(app.exec_())
